version: '3.8'
services:
    # app:
    #     container_name: pj_app
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #         target: $NODE_ENV
    #     command: yarn start:dev
    #     depends_on:
    #         - db
    #         # - redis
    #     env_file:
    #         - .env
    #     ports:
    #         - $PORT:3000
    #     restart: always

    db:
        container_name: pj_db
        image: postgres:16-alpine
        restart: always
        environment:
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_DB: $DB_NAME
        ports:
            - $DB_HOST_PORT:$DB_PORT
        volumes:
            - .docker/db:/var/lib/postgresql/data

    redis:
        container_name: pj_redis
        image: redis:alpine
        expose:
            - 6379
        ports:
            - 6379:6379
        volumes:
            - .docker/redis:/data
        restart: unless-stopped

    # redis_commander:
    #     container_name: redis_commander
    #     image: rediscommander/redis-commander:latest
    #     environment:
    #         - REDIS_HOSTS=local:redis:6379
    #     ports:
    #         - '8088:8081'
    #     depends_on:
    #         - redis

networks:
    default:
        driver: bridge
