name: Deploy to AWS
on:
    pull_request:
        branches: ['production']
        types:
            - closed

env:
    AWS_REGION: ap-southeast-2
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
    SERVER_PUBLIC_IP: ${{ secrets.AWS_PUBLIC_KEY }}

jobs:
    deploy:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: SSH into EC2 and deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ env.SERVER_PUBLIC_IP }}
                  username: ubuntu
                  key: ${{ env.PRIVATE_SSH_KEY }}
                  envs: PRIVATE_SSH_KEY,REGISTRY,REPOSITORY,IMAGE_TAG,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_DEFAULT_REGION,AWS_REGION,NODE_ENV,PORT,DB_HOST,DB_PORT,DB_HOST_PORT,DB_NAME,DB_SCHEMA,SECRET_JWT,MAIL_HOST,MAIL_FROM,MAIL_USER,MAIL_PASS,DB_USERNAME,DB_PASSWORD
                  script: |-
                      cd dat-pj
                      pm2 stop main
                      git pull origin production
                      export NODE_OPTIONS="--max-old-space-size=8192"
                      npm install
                      npm run build
                      TZ=UTC pm2 start dist/src/main.js --env .env
